src/DokkanBundle/Entity/Categoria.php
<?php

namespace DokkanBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;


/**
 * Categories
 */
class Categoria
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $nom;

    protected $entrada;
    
    public function __construct() {
        $this->entrada = new ArrayCollection();
                
    }

    public function __toString(){
        return $this->nom;
    }

    public function getEntrades() {
        return $this->entrada;
    }
    
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Categories
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }
}

src/DokkanBundle/Form/CategoriaType.php
<?php

namespace DokkanBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class CategoriaType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class, array("label"=>"Nombre:","required"=>"false", "attr" =>array(
				"class" => "form-name form-control",
			)))
            ->add('Guardar', SubmitType::class, array("attr" =>array(
				"class" => "form-submit btn btn-success",
			)))
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'DokkanBundle\Entity\Categoria'
        ));
    }
}

src/DokkanBundle/Controller/CategoriaController.php
<?php

namespace DokkanBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use DokkanBundle\Entity\Categoria;
use DokkanBundle\Form\CategoriaType;


class CategoriaController extends Controller
{
	private $session;
	
	public function __construct() {
		$this->session=new Session();
	}

	public function indexAction(){
		$em = $this->getDoctrine()->getEntityManager();
		$categoria_repo=$em->getRepository("DokkanBundle:Categoria");
		$categories=$categoria_repo->findAll();
		
		return $this->render("DokkanBundle:Categoria:index.html.twig",array(
			"categories" => $categories
		));
	}
	
	public function addAction(Request $request){
		$categoria = new Categoria();
		$form = $this->createForm(CategoriaType::class,$categoria);
		
		$form->handleRequest($request);
		
		if($form->isSubmitted()){
			if($form->isValid()){
				
				$em = $this->getDoctrine()->getEntityManager();
				
				$categoria = new Categoria();
				$categoria->setNom($form->get("nom")->getData());
				
				$em->persist($categoria);
				$flush = $em->flush();
				
				if($flush==null){
					$status = "Categoria creada correctament";
				}else{
					$status ="Categoria no afegida";
				}
				
			}else{
				$status = "Categoria no afegida perquè el formulari no és vàlid";
			}
			
			$this->session->getFlashBag()->add("status", $status);
			return $this->redirectToRoute("dokkan_index_categoria");
		}
		
		
		return $this->render("DokkanBundle:Categoria:add.html.twig",array(
			"form" => $form->createView()
		));
	}
	
	public function deleteAction($id){
		$em = $this->getDoctrine()->getEntityManager();
		$categoria_repo=$em->getRepository("DokkanBundle:Categoria");
		$categoria=$categoria_repo->find($id);
		
		if(count($categoria->getEntrades())==0){
			$em->remove($categoria);
			$em->flush();
		}
		
		return $this->redirectToRoute("dokkan_index_categoria");
	}
        
        public function editAction(Request $request, $id){
		$em = $this->getDoctrine()->getEntityManager();
		$categoria_repo=$em->getRepository("DokkanBundle:Categoria");
		$categoria=$categoria_repo->find($id);
		
		$form = $this->createForm(CategoriaType::class,$categoria);
		
		$form->handleRequest($request);
		
		if($form->isSubmitted()){
			if($form->isValid()){
				
				$categoria->setNom($form->get("nom")->getData());
				
				$em->persist($categoria);
				$flush = $em->flush();
				
				if($flush==null){
					$status = "La categoria se ha editado correctamente !!";
				}else{
					$status ="Error al editar la categoria!!";
				}
				
			}else{
				$status = "La categoria no s'ha editat, porque el formulario no és vàlido !!";
			}
			
			$this->session->getFlashBag()->add("status", $status);
			return $this->redirectToRoute("dokkan_index_categoria");
		}
		
		return $this->render("DokkanBundle:Categoria:edit.html.twig",array(
			"form" => $form->createView()
		));
	}
        
}

src/DokkanBundle/Resources/views/Categoria/add.html.twig
{% extends "DokkanBundle::layout.html.twig"%}
{% block content %}
            
    <div class="col-lg-6">
        <h2>Afegir Categories</h2> 
        <hr/>
        {{form_start(form, {'action':'', 'method':'POST'})}}
        {{form_end(form)}}
    </div>
            
    <div class="clearfix"></div>
{% endblock %}

src/DokkanBundle/Resources/views/Categoria/edit.html.twig
{% extends "DokkanBundle::layout.html.twig"%}
{% block content %}
            
    <div class="col-lg-6">
        <h2>Editar Categoria</h2> 
        <hr/>
        {{form_start(form)}}
        {{form_end(form)}}
    </div>
            
    <div class="clearfix"></div>
{% endblock %}

src/DokkanBundle/Resources/views/Categoria/index.html.twig
{% extends "DokkanBundle::layout.html.twig" %}

{% block content %}
    <div class="col-lg-6">
        <h2>Llistat Categories</h2>
        <hr/>
        <a href="{{path("dokkan_add_categoria")}}" class="btn btn-success">Afegir categoria</a>
        <hr/>
        {% for message in app.session.flashbag().get('status') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
        <table class="table table-bordered">
            <tr>
                <th>Nom</th>
                <th>Editar</th>
                <th>Esborrar</th>
            </tr>
            {% for categoria in categories %}
                <tr>
                    <td>{{ categoria.nom }}</td>
                    <td><a href="{{path("dokkan_edit_categoria", {"id":categoria.id})}}" class="btn btn-warning">Editar</a></td>
                    <td>
                        {% if categoria.entrades|length == 0 %}
                            <a href="{{path("dokkan_delete_categoria", {"id":categoria.id})}}" class="btn btn-danger">Eliminar</a>
                        {% else %} 
                           Categoria en uso
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="clearfix"></div>
{% endblock %}